picture_path: env-art
preview:
  filename: train-station
  original: train-station.webp
  sizes:
  - train-station.webp
  thumbnail: train-station-thumbnail.webp
pictures:
- filename: train-station
  original: train-station.webp
  sizes:
  - train-station.webp
  thumbnail: train-station-thumbnail.webp
  title: Minimalistic Train Station
- filename: floating-island
  original: floating-island.webp
  sizes:
  - floating-island.webp
  thumbnail: floating-island-thumbnail.webp
  title: Low Poly Floating Island
- filename: blacksmith
  original: blacksmith.webp
  sizes:
  - blacksmith.webp
  thumbnail: blacksmith-thumbnail.webp
  title: Blacksmith Render
- filename: potion-dungeon
  original: potion-dungeon.webp
  sizes:
  - potion-dungeon.webp
  thumbnail: potion-dungeon-thumbnail.webp
  title: Potion Dungeon
- filename: alchemy-bench
  original: alchemy-bench.webp
  sizes:
  - alchemy-bench.webp
  thumbnail: alchemy-bench-thumbnail.webp
  title: Alchemy Bench